import loadable from '@/utils/loader'
export const Home = loadable(() => import('@/pages/home'))
export const Login = loadable(() => import('@/pages/login'))
export const Choosechild = loadable(() => import('@/pages/choosechild'))
export const Pageone = loadable(() => import('@/components/pageone'))
export const Pagetwo = loadable(() => import('@/components/pagetwo'))
export const Pagethree = loadable(() => import('@/components/pagethree'))
export const Pagefour = loadable(() => import('@/components/pagefour'))
export const Logindefs = loadable(() => import('@/components/login'))
export const Product = loadable(() => import('@/components/product'))
export const Productone = loadable(() => import('@/components/productone'))
export const Producttwo = loadable(() => import('@/components/producttwo'))
